name: CI
on:
  pull_request:
  push:
    branches:
      - main

env:
  CI: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3.1.0
      with:
        node-version: 16
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint --if-present

    - name: Build
      run: npm run build --if-present

    - name: Test
      run: npm test --if-present
